services:
  php:
    container_name: cn2e-php
    build:
      context: ./docker/php
    volumes:
      - ./cn2e-app:/var/www/html
      - cn2e_bash_history:/root
    working_dir: /var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - cn2e-network

  apache:
    container_name: cn2e-apache
    build:
      context: ./docker/apache
    ports:
      - '8080:80'
    volumes:
      - ./cn2e-app:/var/www/html
    depends_on:
      - php
      - mariadb
    networks:
      - cn2e-network

  mariadb:
    container_name: cn2e-db
    image: mariadb:10.11
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cn2e
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - cn2e-network

  phpmyadmin:
    container_name: cn2e-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: cn2e-db
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - mariadb
    networks:
      - cn2e-network

  tailwind:
    build:
      context: ./docker/tailwind
    container_name: cn2e-tailwind
    working_dir: /var/www/html
    volumes:
      - ./cn2e-app:/var/www/html
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - cn2e-network

volumes:
  db_data:
  cn2e_bash_history:

networks:
  cn2e-network:
    driver: bridge